CREATE TABLE employees(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_code VARCHAR(20) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE ,
    phone_number VARCHAR(20) NOT NULL,
    date_of_birth DATE,
    date_of_joining DATE NOT NULL,
    designation VARCHAR(100) NOT NULL ,
    salary DECIMAL(12,2) NOT NULL,
    status VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);